pro_dash/dash_app/urls.py
from django.conf.urls import include , url
from dash_app.views import *
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

app_name = 'dash_app'

urlpatterns = [

    url(r'^signup/$', signup, name='signup'),
    url(r'^signup/login/$', auth_views.login, {'template_name': 'dash_app/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^login/KPIs_dashboard/$', home, name='home'),
    url(r'^profile/', TemplateView.as_view(template_name='profile.html')),
    url(r'^saved/', SaveProfile , name='SaveProfile'),
]

pro_dash/pro_dash/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url('', include('dash_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pro_dash/dash_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# Create your models here.
from django.db import models

class Profile(models.Model):
   name = models.CharField(max_length = 50)
   picture = models.ImageField(upload_to = 'pictures')

   class Meta:
      db_table = 'profile'

pro_dash/dash_app/forms.py
#-*- coding: utf-8 -*-
from django import forms

class ProfileForm(forms.Form):
   name = forms.CharField(max_length = 100)
   picture = forms.ImageField()

pro_dash/dash_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.views import login
from django.views.decorators.csrf import csrf_exempt

from dash_app.forms import ProfileForm
from dash_app.models import Profile



@csrf_exempt
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            print(user)
            login(request, user)
            print(login(request, user))
            return render(request, 'dash_app/login.html')
    else:
        form = UserCreationForm()
    return render(request, 'dash_app/signup.html', {'form': form})



def home(request):
    return render(request,"dash_app/index.html",{})



def SaveProfile(request):
    saved = False

    if request.method == "POST":
        # Get the posted form
        MyProfileForm = ProfileForm(request.POST, request.FILES)

        if MyProfileForm.is_valid():
            profile = Profile()
            profile.name = MyProfileForm.cleaned_data["name"]
            profile.picture = MyProfileForm.cleaned_data["picture"]
            profile.save()
            saved = True
    else:
        MyProfileForm = ProfileForm()

    return render(request, 'saved.html', locals())

pro_dash/dash_app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>My Project</title>
    </head>

    <body>
    {% block content %}{% endblock content %}
    </body>
</html>

pro_dash/dash_app/templates/dash_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
	<title>Login V16</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'dash_app/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href= "{% static 'dash_app/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body background="{% static 'dash_app/images/bg-01.jpg' %}">

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					Account Login
				</span>
				<form method="post" class="login100-form validate-form p-b-33 p-t-5" action="{%url 'dash_app:home'%}">
                    {% csrf_token %}
					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input id="id_username" class="input100" type="text" name="username" placeholder="User name">
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input id="id_password" class="input100" type="password" name="pass" placeholder="Password">
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					<div class="container-login100-form-btn m-t-32">
						<button type="submit" class="login100-form-btn">
							Login
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static 'dash_app/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'dash_app/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'dash_app/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'dash_app/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'dash_app/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'dash_app/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'dash_app/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'dash_app/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'dash_app/js/main.js' %}"></script>

</body>
</html>

pro_dash/dash_app/templates/dash_app/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
	   {% load staticfiles %}
	<title>Login V13</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="icon" type="image/png" href="{% static 'dash_app/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href= "{% static 'dash_app/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'dash_app/css/main.css' %}">
</head>
<body style="background-color: #999999;" >

	<div class="limiter">
		<div class="container-login100" >
			<div class="login100-more">
                <img src="{% static 'dash_app/images/bg-02.jpg' %}">
            </div>


              <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
			<div class="wrap-login100 p-l-50 p-r-50 p-t-72 p-b-50">

			</div>
		</div>
	</div>

<!--===============================================================================================-->
	<script src="{% static 'dash_app/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'dash_app/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'dash_app/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'dash_app/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'dash_app/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'dash_app/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'dash_app/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'dash_app/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'dash_app/js/main.js' %}"></script>

</body>
</html>

pro_dash/dash_app/templates/profile.html
<html>
   <body>
       <form name = "form" enctype = "multipart/form-data" action = "{% url 'dash_app:SaveProfile' %}"
      method = "POST" >{% csrf_token %}

         <div style = "max-width:470px;">
            <center>
               <input type = "text" style = "margin-left:20%;"
               placeholder = "Name" name = "name" />
            </center>
         </div>

         <br>

         <div style = "max-width:470px;">
            <center>
               <input type = "file" style = "margin-left:20%;"
                  placeholder = "Picture" name = "picture" />
            </center>
         </div>

         <br>

         <div style = "max-width:470px;">
            <center>

               <button style = "border:0px;background-color:#4285F4; margin-top:8%;
                  height:35px; width:80%; margin-left:19%;" type = "submit" value = "upload" >
                  <strong>upload</strong>
               </button>

            </center>
         </div>

      </form>

   </body>
</html>

pro_dash/dash_app/templates/saved.html
<html>
   <body>

      {% if saved %}
         <strong>Your profile was saved.</strong>

      <h2>{{ profile.name }}</h2>
         <!--<img src="{{ profile.picture.url}}" >-->
         <img src="{{ profile.picture.url }}" width="200" height="200" alt="{{ profile.picture.name }}">


      {% endif %}

      {% if not saved %}
         <strong>Your profile was not saved.</strong>
      {% endif %}

   </body>
</html>